steps:
  # Step 0: Compila l'app Java con Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'  # cartella del progetto Java
    
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app', '.']

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - demo-app
      - --image=gcr.io/$PROJECT_ID/demo-app
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/demo-app

options:
      logging: CLOUD_LOGGING_ONLY
      default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
